name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      IMAGE_NAME: haytok.github.io:latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b572f7b1a1c2d41efaab43d504f68d215c3cd727  # v0.5.4
        with:
            min-severity: high
            advanced-security: false

      - name: Build Docker image
        run: |
          docker build -t ${IMAGE_NAME} .

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

      - name: Build with Hugo
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            -u $(id -u):$(id -g) \
            -e HUGO_CACHEDIR=/tmp/hugo_cache \
            ${IMAGE_NAME} \
            --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      pages: write
      id-token: write
    needs: build
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5.0.0
